### PR TITLE
Bottom layout

### LINKED ISSUE #16: Bottom Navigation in second layout.
- [ ] Simply Just Add bottom navigation with 3 tabs in the second layout activity, it is not required to make it work fully functional.

### PR DESCRIPTION
**Pull request by sanchi0204**
Resolves #16 

Design:
bottom

Uses:
Material Bottom Navigation View
Vector Icons

Follows:
Material Design guidelines

### CODE REVIEW

**Comment by HemangNakarani** [comment]
Thank You @sanchi0204 for your contribution, But for now, I can't approve your PR, and you have already solved some issues in this project. Now You can learn new things in android or can think about what we can add more to our project.

But Don't worry work should not go in vain, I'll give you 25 points for this.

**Comment by sanchi0204** [comment]
> Thank You @sanchi0204 for your contribution, But for now, I can't approve your PR, and you have already solved some issues in this project. Now You can learn new things in android or can think about what we can add more to our project.
> 
> But Don't worry work should not go in vain, I'll give you 25 points for this.

So now I need to contribute to a new project?

**Comment by HemangNakarani** [comment]
> > Thank You @sanchi0204 for your contribution, But for now, I can't approve your PR, and you have already solved some issues in this project. Now You can learn new things in android or can think about what we can add more to our project.
> > But Don't worry work should not go in vain, I'll give you 25 points for this.
> 
> So now I need to contribute to a new project?

No, you will have to contribute in this project only for SLoP, just wait until I open new issues. We have many things to do. Utilize this time to learn some new concepts of android, which are not so familiar with you.

**Comment by HemangNakarani** [comment]
give @sanchi0204 25 points

**Pull request closed without merging**
