### PR TITLE
Implementing Room DB 

### PR DESCRIPTION
**Pull request by ashishpatel16**
@HemangNakarani @prit29 
These are the changes I've made so far. Can you review them and let me know if the naming conventions and files are okay?
Also suggest improvements and what more to add!

### CODE REVIEW

**Comment by HemangNakarani** [comment]
Great !! I'm sleeping now, let's do it today in day😅

**Comment by ashishpatel16** [comment]
Oops Sorry! 😅

**Comment by ashishpatel16** [comment]
@HemangNakarani 
Did you review my code? 
Can I continue with this format? 
Also guide me on how the Repository class is to be structured, I followed the tutorial and android docs. I'm still trying to figure out how to manage different threads for executing queries. The reference video uses a lot of messy Async tasks. Any better way to do that?

**Comment by HemangNakarani** [comment]
> @HemangNakarani
> Did you review my code?
> Can I continue with this format?
> Also guide me on how the Repository class is to be structured, I followed the tutorial and android docs. I'm still trying to figure out how to manage different threads for executing queries. The reference video uses a lot of messy Async tasks. Any better way to do that?

Yeah @ashishpatel16 I have reviewed your code I felt something was missing. You will need to implement the whole MVVM structure. Refer [this repo](https://github.com/devsoftzz/MVVM-Android). My friend has built it. He is fetching API, instead of it, we will have to get data from the database. You will need one Repository and one ViewModel Folder. Async fetches will be done in the Repository. You already know it right !!. We'll use async tasks here. It will be quite easy. Try to learn MVVM and Async tasks. Make a simple APP using MVVM and DAO. Then try to fit it in our project.

I'll send you the link as soon as I get good documentation or video.

Good Luck.

**Comment by ashishpatel16** [comment]
> > @HemangNakarani
> > Did you review my code?
> > Can I continue with this format?
> > Also guide me on how the Repository class is to be structured, I followed the tutorial and android docs. I'm still trying to figure out how to manage different threads for executing queries. The reference video uses a lot of messy Async tasks. Any better way to do that?
> 
> Yeah @ashishpatel16 I have reviewed your code I felt something was missing. You will need to implement the whole MVVM structure. Refer [this repo](https://github.com/devsoftzz/MVVM-Android). My friend has built it. He is fetching API, instead of it, we will have to get data from the database. You will need one Repository and one ViewModel Folder. Async fetches will be done in the Repository. You already know it right !!. We'll use async tasks here. It will be quite easy. Try to learn MVVM and Async tasks. Make a simple APP using MVVM and DAO. Then try to fit it in our project.
> 
> I'll send you the link as soon as I get good documentation or video.
> 
> Good Luck.

Yeah Sure. I'll refer the code and read more articles from my side as well. Will make good progress soon. Thankyou !! 🤞

**Comment by ashishpatel16** [comment]
@HemangNakarani I've finally made some changes and tested them out as well. Added some temporary test functions inside the HelpActivity, so you can head over to help activity to review them and checkout the logs for the dummy contests I added.

I think it's quite MVVM-ish now😅 Do let me know where to improve!! 😃🤞

**Comment by ashishpatel16** [comment]
@HemangNakarani Did you review the changes sir?
Do I need to make more changes or some improvements in the code?

**Comment by HemangNakarani** [comment]
> @HemangNakarani Did you review the changes sir?
> Do I need to make more changes or some improvements in the code?

I have seen the PR, but not yet reviewed because our exams are going on, will do it soon as possible.

**Review by HemangNakarani — CHANGES_REQUESTED** [review]
## Amazing Work @ashishpatel16 

## Just few thing needed to be perfect.

- POJO fields
  - Just add `platform` field in contest POJO, `title` will be the title of any contest.
- Queries Change
  - Add Query for Delete all tuples
  - Remove query for retrieving contest by title, and add a query for retrieving contest by platform
  - Get Contest by time, like you have given time segment, retrieve just those contests which has starttime in given time segment. For it you will have to learn basic SQL queries, which I don't think take much time.
- Run the app, and check [http://localhost:8080/](http://localhost:8080/) in your phone's browser. It's for debugging database.
## Good Luck

**Comment by ashishpatel16** [comment]
@HemangNakarani 
Check out the changes!! 
Same strategy however for testing. But this time I used real contest data from our API. This issue has helped me learn so much!!🤞
Do suggest further improvements.

**Review by HemangNakarani — CHANGES_REQUESTED** [review]
## Everything is Just Perfect

but because of I have just merged HelpActivity and its Layout from other participant, it has got some conflicts in HelpActivity because you have also tested database in same Activity, what I suggest is to make a new temporary activity for testing, so we could delete it later. Otherwise great work !! 👍

**Comment by ashishpatel16** [comment]
@HemangNakarani 
Done!
Changes Made -
* Made temporary activity named RoomActivity. Logs can be found there.
 
* Although I couldn't think of some decent UI changes to navigate to temporary activity because then later a lot of code will have to be again deleted carefully, so I did a Dirty fix that We can navigate to notifications activity and it will automatically take us to RoomActivity. This way only one line of code will have to be erased from Notifications Activity.

**Review by HemangNakarani — APPROVED** [review]
Thanks For the PR, @ashishpatel16 !! 👍🏻

**Pull request merged**
