### PR TITLE
Added Checkboxes Of Google, LeetCode and Refactored Padding/Margin

### LINKED ISSUE #34: Add New Check Boxes in SettingsActivity
## Following CheckBoxes Should Be included in Setting activity
- codeforces.com 
- codechef.com
- hackerearth.com 
- leetcode.com 
- topcoder.com
- atcoder.jp
- hackerrank.com 
- codingcompetitions.withgoogle.com spoj.com

### - Refactor Margins/Paddings : Every CardView Should Have **8dp** MarginTop, Remove Padding in ScrollView

### PR DESCRIPTION
**Pull request by fenu28**
Changes Made:

- Added LeetCode and Google to tab item list.
- Added Checkboxes of Leetcode, Google
- Added Codeforces as default platform, Codeforces get selected automatically after all checkboxes are deselected.
- Added constant strings for Leetcode and Google in Constants.java file
- Removed Paddding of ScrollView in activity_settings.xml
- marginTop of Card Design set to 8dp

Fixes #34

### CODE REVIEW

**Comment by fenu28** [comment]
@HemangNakarani plz review the PR and tell if any changes are required.

**Review by HemangNakarani — APPROVED** [review]
Good Work @fenu28 !!

**Comment by HemangNakarani** [comment]
- Just do one thing now you can see these different margins between cards. first, fix it. and give horizontal margin also 8dp. Finally your card's all sides will have margin of 8 dp from the corresponding edge.

- image

**Comment by fenu28** [comment]
Ok on it!

**Comment by fenu28** [comment]
@HemangNakarani PR done for the activity_settings.xml margin problem. Please review it.

**Pull request merged**
