### PR TITLE
Added toggle buttons and fragments in second layout.

### PR DESCRIPTION
**Pull request by dishantvyas15**
This PR is expected to solve issue #31 
@HemangNakarani, @prit29 Please provide the names of the fragments so that I can add icons and labels in the toggle buttons. Also mention if there are any changes to be made.

### CODE REVIEW

**Review by HemangNakarani — CHANGES_REQUESTED** [review]
@dishantvyas15 Good Work, I want to clarify some things.

- Keep name of Fragment Files as I have commented.
- Here You have given integer Id it's not good practice, You can use like R.id.button1 for getting id.
image

So please change these things.

**Review by dishantvyas15 — COMMENTED** [review]
@HemangNakarani, I've made the changes. Review requested.

**Review by HemangNakarani — CHANGES_REQUESTED** [review]
Yupp that's fine now.
I want to suggest some improvisations to make it efficient and attractive.

- Every time you click on the button that fragment being recreated means every time it executes ```onCreate``` Method, that should not happen. Instead of using replace fragment use a trick of hide and show. Search about it a little bit, you'll get the solution.
- Keep Buttons to the top instead of the bottom and keep some margin around it, about 8dp !!
- Is it possible to add some animation while changing between fragments?

## Amazing Work Otherwise !! 👍

**Comment by dishantvyas15** [comment]
Screenshot 2020-10-20 131820

@HemangNakarani I kept the buttons at the bottom due to this instruction. Should I change?

I'll implement hide-show feature in the fragments and look into the animation part.

**Comment by HemangNakarani** [comment]
> Screenshot 2020-10-20 131820
> 
> @HemangNakarani I kept the buttons at the bottom due to this instruction. Should I change?
> 
> I'll implement hide-show feature in the fragments and look into the animation part.

@dishantvyas15 
Sorry that was written by mistake, but now keep it on top 👍

**Comment by dishantvyas15** [comment]
@HemangNakarani, I may be wrong but I found that animations cannot be applied to fragments if I use show/hide to change them. Animation seems to work only while replacing fragments. Is there any way to do both the things simultaneously ??

**Comment by HemangNakarani** [comment]
> @HemangNakarani, I may be wrong but I found that animations cannot be applied to fragments if I use show/hide to change them. Animation seems to work only while replacing fragments. Is there any way to do both the things simultaneously ??

Yupp, it's not there. But what I am saying that you can show animation in starting in `onCreateView` of every fragment. Check UBER app when it opens. It just animates some View and objects in fragment itself. Maybe this can be done in our case also.  You can use any good ready-made animation from the internet, you don't need to write it yourself, you want to do it yourself then also it's ok.

**Pull request closed without merging**
