### PR TITLE
Issue #15 solved.

### PR DESCRIPTION
**Pull request by dishantvyas15**
The PR is expected to solve issue #15 
Review requested.

### CODE REVIEW

**Comment by dishantvyas15** [comment]
@HemangNakarani Can you please have a look into this?

**Comment by HemangNakarani** [comment]
**Great !!!** @dishantvyas15 your logic is all correct, now just do one thing when user switches layout and presses the back button then user should not go in the previous layout. For it you need to finish activity while switching layouts.

One more thing just update your repo with the master branch code becayse I have just merged another PR.

**Comment by HemangNakarani** [comment]
@dishantvyas15 see my pr #49 You'll get the idea, it was too simple.

**Comment by dishantvyas15** [comment]
I got your point.
Currently, I'm stuck with some conflicts and fetch-pull things. Making a commit in a while.

**Comment by dishantvyas15** [comment]
I think now it's done.
Review requested.

**Review by HemangNakarani — CHANGES_REQUESTED** [review]
- See this part in my PR. `finish()` should not be written before starting another activity. This is like you have finished activity then you are using activity to open another activity. It is a bad practice. Also here you should use `finishAffinity()`
image

-  Don't define constants like this, you can define constant variable in Constants.java file then you can use wherever you want, see my PR #49
image

- Don't remove this lines instead you can conditionally open currently selected layout activities
image

- This part is removed from last PR in `LayoutOneActivity`. If you feel like you are stuck in pull and merge, I suggest you to delete your forked repo and fork it again from main repo. Then do changes as mentioned. It won't take more than 15 minutes.
image

## For references, see my PR #49

**Comment by dishantvyas15** [comment]
@HemangNakarani, I've made all the changes as directed. Before I make the commit, one question:
Should I write the `loadActivity()` and `saveActivity()` functions in `Methods.java` ??

**Comment by dishantvyas15** [comment]
I had deleted my forked repo and created a new one. As a consequence, I've made a new pull request (#51) with all the updations.
Please review it.

**Pull request closed without merging**
