### PR TITLE
settings layout design

### PR DESCRIPTION
**Pull request by sanchi0204**
The PR solves #7 

Design:
settings

Follows:
Material Design Guidelines

Uses:
Material CheckBox
Material Switch

### CODE REVIEW

**Comment by HemangNakarani** [comment]
@sanchi0204 Great work, but I wanted to make design somewhat more attractive like using cards for each section, also it should have the option to turn on/off notifications and the time span option for how many days of contests would you like to show. That's why I have told to make the design first in rough. Don't worry I'm giving you 25 points for this.

**Comment by HemangNakarani** [comment]
give @sanchi0204 25 points

**Comment by sanchi0204** [comment]
> @sanchi0204 Great work, but I wanted to make design somewhat more attractive like using cards for each section, also it should have the option to turn on/off notifications and the time span option for how many days of contests would you like to show. That's why I have told to make the design first in rough. Don't worry I'm giving you 25 points for this.

Okay, I am doing the required changes

**Comment by sanchi0204** [comment]
@HemangNakarani  Pls have a look at this. Is this fine?

ezgif com-gif-maker

Shall I make a PR for this?

**Comment by HemangNakarani** [comment]
@sanchi0204 this looks great !!!

**Comment by HemangNakarani** [comment]
give @sanchi0204 25 points

**Comment by HemangNakarani** [comment]
give @sanchi0204 25 points

**Comment by sanchi0204** [comment]
@HemangNakarani you have merged the old layout design.
I have not committed the new design yet.

**Comment by HemangNakarani** [comment]
Ohh !! just realised that one, now push the new code I'll merge it.

**Comment by sanchi0204** [comment]
shall I make a new PR?

**Comment by HemangNakarani** [comment]
Yes, please! I have already given points for this Design.

**Pull request merged**
