### PR TITLE
Switch layouts - issue solved.

### PR DESCRIPTION
**Pull request by dishantvyas15**
Hello!
I have solved the "Switching Layouts" issue.
Please go through the changes and instruct if something is needed to be modified.

### CODE REVIEW

**Review by HemangNakarani — CHANGES_REQUESTED** [review]
**Great Work !!!**

I want to point out that some things.

- Whereever you are using ```getSharedPreferences``` and ```setSharedPreferences``` just replace it with already defined in Methods.java file. ex: in ```loadLastActivity``` function
- Remove Redundunt code, like you have marked some code snippets as commented, remove them and keep codebase clean.
- In SplashActivity You are not using ```lastActivity``` variable, remove redundent variables also, try to make objects as less as possible.
- Connect Activity Switching with that stack icon, it is defined under ```onCreateOption``` menu in LayoutOneActivity
image
- Also Follow Instructions that I have sent you on Gitter.

**Comment by dishantvyas15** [comment]
Have understood all the points. Thank you!
Making the mentioned changes soon..

**Comment by HemangNakarani** [comment]
@dishantvyas15 Please, Resolve conflicts on this PR.

***Great Work Otherwise*** 👍

**Comment by dishantvyas15** [comment]
On it.

**Comment by HemangNakarani** [comment]
Any Updates ? @dishantvyas15

**Comment by dishantvyas15** [comment]
@HemangNakarani, review requested w.r.t. commit #abedc57

**Comment by dishantvyas15** [comment]
I've made a change in the `onBackPressed()` method of the `Settings.java` file; replaced the `startActivity()` that used a new intent (at the end of the function), by a `finish()` call.

**Comment by HemangNakarani** [comment]
@dishantvyas15 please solve the conflicts on this PR.

**Comment by dishantvyas15** [comment]
Conflicts resolved.

**Comment by HemangNakarani** [comment]
Hiii @dishantvyas15, I suggest you to merge the master branch in your project and if it is running after that, then make PR. Currently, I have seen your project it couldn't run because of another reason, So do as I suggested, do changes if needed and then make PR.

**Comment by dishantvyas15** [comment]
@HemangNakarani I got my mistake, I had not updated my forked repo and that's why it is leading to numerous conflicts now. I'll make a new pull request soon, after getting things sorted.

**Pull request closed without merging**
