### PR TITLE
Added View Pager and fragments

### PR DESCRIPTION
**Pull request by ashishpatel16**
Quick overview - 

* Created Blank fragments for individual contests in **Fragments package**.
* Removed the existing Linear layout and TextViews from layoutOneActivity and added a ViewPager.
* Created ViewPagerAdapter Class in **Adapters package** and setup the mechanism for addition of tabs.

Also @mentors, I've added a method **getFragmentsList( )** to return a list of fragments which could be later used by the app's backend. Couldn't think of some other way to provide a reference to those fragments. Is this way helpful?

### CODE REVIEW

**Comment by HemangNakarani** [comment]
@ashishpatel16 solve conflicts plz

**Comment by ashishpatel16** [comment]
@HemangNakarani Conflicts resolved!!

**Comment by ashishpatel16** [comment]
@HemangNakarani  But this PR still needs an update. Fragments for newly added checkboxes **Leetcode** and **google** are yet to be created.

**Comment by ashishpatel16** [comment]
> @HemangNakarani But this PR still needs an update. Fragments for newly added checkboxes **Leetcode** and **google** are yet to be created.

@HemangNakarani 
Say no more😅 I added them as well. 
Pls review!

**Review by HemangNakarani — APPROVED** [review]
**Amazing Work !!**
@ashishpatel16

**Comment by HemangNakarani** [comment]
give @ashishpatel16 75 points

**Pull request merged**
