### PR TITLE
Make activities in appbar

### PR DESCRIPTION
**Pull request by ashishpatel16**
@HemangNakarani @prit29 
Solving #32 
I'm not confident about the changes I made in **activity_settings.xml** file, Is this a valid way to do that? 
It seemed to work though!!

Do review and suggest improvements!

### CODE REVIEW

**Review by HemangNakarani — CHANGES_REQUESTED** [review]
Hey @ashishpatel16 it seems nice, but I want to suggest one idea to remove redundancy.

- Make a layout that contains just an app bar.
- import it in activity layouts when needed. Simple.

You will not need to write the same code every time. Like this, you can make reusable components.

So please make changes accordingly. Great work otherwise !!!

**Comment by ashishpatel16** [comment]
@HemangNakarani Changes made! 
Review them and let me know whether I made the right changes you were expecting 😅

**Review by HemangNakarani — APPROVED** [review]
Nice !! 👍

**Comment by HemangNakarani** [comment]
give @ashishpatel16 25 points

**Pull request merged**
