### PR TITLE
Added constants file

### PR DESCRIPTION
**Pull request by ashishpatel16**
Review the changes, I replaced the constants I found so far and all newer constants should be introduced to the Utils>Constants.java file as we may need them. 
Do Suggest further changes Sir! 😄

### CODE REVIEW

**Comment by HemangNakarani** [comment]
Good Work @ashishpatel16 , just resolve the conflicts in this PR, They are just small conflicts. Then after I'll approve it

**Comment by ashishpatel16** [comment]
Pheeew! 
Conflict resolution done. I learnt a new thing here as well about resolving conflicts. 
Thankyou @HemangNakarani 😅

**Comment by HemangNakarani** [comment]
Great !!! I am glad to know that you are learning 😊

**Review by HemangNakarani — APPROVED** [review]
Great !! 👍 👍

**Comment by HemangNakarani** [comment]
give @ashishpatel16 25 points

**Review by HemangNakarani — COMMENTED** [review]
@ashishpatel16 can you change constants in Settings file also ?
image
image

**Comment by ashishpatel16** [comment]
Sure Sir! 
I've made those changes.

But @HemangNakarani, How do I make the code look more organized?

This snippet occurs a lot -
``Gson gson = new Gson();
        SharedPreferences.Editor editor = preferences.edit();
        String text = gson.toJson(checkedItem);
        editor.putString(Constants.TAB_ITEMS_ARRAYLIST_KEY,text);
        editor.apply();``

Should we create a separate method for it in Utils>Methods.java file?

**Pull request merged**
