### PR TITLE
Added Dynamic tab layouts in LayoutOneActivity.

### PR DESCRIPTION
**Pull request by ashishpatel16**

### CODE REVIEW

**Comment by ashishpatel16** [comment]
Tested the code on physical device, works well as expected.

**Comment by HemangNakarani** [comment]
@ashishpatel16 your logic is correct but, try to use shared preferences, you can save the array of checked platforms into the SharedPreferences, and when you open activity you can get that array, and simply show those tabs only. If you can do this it would be great !!

**Review by HemangNakarani — CHANGES_REQUESTED** [review]
@ashishpatel16 your logic is correct but, try to use shared preferences, you can save the array of checked platforms into the SharedPreferences, and when you open activity you can get that array, and simply show those tabs only. If you can do this it would be great !!

- Hint: You can save array into SharedPreferences by converting it in json format

**Comment by ashishpatel16** [comment]
Sir I faced troubles commiting to this branch. Had to make a newer one. Sorry for that! 😅

**Pull request closed without merging**
