### PR TITLE
Base activity for navigation drawer added

### LINKED ISSUE #4: Make Inherited Side Navigation Drawer For Two Activities
We have two layouts for displaying coding contests, so make a drawer for both activities which is inherited from abstract base activity.

### PR DESCRIPTION
**Pull request by sanchi0204**
Fixes #4 

Added navigation drawer (Material design guidelines)

Commented the earlier parts of the code which were not relevant to the new changes.

Added a temporary code in LayoutOneActivity.java for testing purpose

### CODE REVIEW

**Comment by sanchi0204** [comment]
@HemangNakarani pls review the PR and tell me if any changes required

**Review by HemangNakarani — CHANGES_REQUESTED** [review]
### I want to point out some minor issues
- Fix this DrawerLayout, it is getting out from screen.
image
  - Hint: Use ```CoordinatorLayout``` inside ```DrawerLayout```
  - FrameLayout for content placeholder will have attribute ```app:layout_behavior="@string/appbar_scrolling_view_behavior"```
  - See ```LayoutOneActivity``` for reference, it was already made in it.
- Write these two methods also in BaseActivity, remove it from ```LayoutOneActivity```
   - ```onCreateOptionsMenu``` and ```onOptionsItemSelected```
- Clean the codebase. You can now remove the commented part and other redundant part of code if it is not needed. Keep That sample code for switching activities.

### Great Work Otherwise, hope you have learned something new !!
<br>

**Comment by sanchi0204** [comment]
@HemangNakarani I have made the changes. Pls check

**Review by HemangNakarani — APPROVED** [review]
## Great !!! 👍

**Comment by HemangNakarani** [comment]
give @sanchi0204 150 points

**Comment by sanchi0204** [comment]
> ## Great !!! 👍

Thank you

**Pull request merged**
